### ISSUE TITLE
Compress the kernel image

### ISSUE THREAD

**Issue by siwadon** [idewz/rpi-xboot#5]
Sending a compressed kernel image would definitely reduce the transfer time and make the iterative development fun again. 🎉 

Here is the interesting list of algorithms / libraries:
- [zlib](https://github.com/madler/zlib)
- [bzip2](http://bzip.org/index.html)
- [lzma](https://www.7-zip.org/sdk.html)
- [snappy](https://github.com/google/snappy) C++ with C bindings

#### Benchmarking
https://quixdb.github.io/squash-benchmark/

```bash
-rwxr-xr-x   1 idewz  staff  587952 Mar 28 16:51 kernel7.img
-rw-r--r--   1 idewz  staff   83184 Apr  3 15:56 kernel7.img.bz2
-rw-r--r--   1 idewz  staff   91328 Apr  3 16:40 kernel7.img.gz
-rw-r--r--   1 idewz  staff  101092 Apr  3 16:25 kernel7.img.lz4
-rw-r--r--   1 idewz  staff   62244 Apr  3 15:55 kernel7.img.lzma
-rw-r--r--   1 idewz  staff  162184 Apr  3 16:21 kernel7.img.snappy
-rw-r--r--   1 idewz  staff   62300 Apr  3 16:01 kernel7.img.xz
```

Our kernel image is quite small, only 587k. The compression/decompression speed might not be a problem.

#### Tasks:
- [x] Check out compression algorithms / libraries
- [x] Implement POC decompressor program
- [x] Implement LZMA compression in `rpi-install.py`
- [x] Implement LZMA decompression in the `bootloader`
- [x] Update README
